mirror/communitytools/trunk/sphenecoll/sphene/sphboard/urls.py
from django.conf.urls.defaults import *

from django.conf.urls.defaults import *


urlpatterns = patterns('',
                       (r'^$', 'django.views.generic.simple.redirect_to', {'url': 'show/0/'}),
                       )
urlpatterns += patterns('sphene.sphboard.views',
                        (r'^show/(?P<category_id>\d+)/$', 'showCategory'),
                        (r'^latest/(?P<category_id>\d+)/$', 'showCategory', { 'showType': 'threads' }),
                        (r'^thread/(?P<thread_id>\d+)/$', 'showThread'),
                        (r'^options/(?P<thread_id>\d+)/$', 'options'),
                        (r'^post/(?P<category_id>\d+)/$', 'post'),
                        (r'^vote/(?P<thread_id>\d+)/$', 'vote'),
                       )

mirror/communitytools/trunk/sphenecoll/sphene/sphwiki/urls.py
from django.conf.urls.defaults import *

from django.conf.urls.defaults import *



urlpatterns = patterns('',
                       (r'^$', 'django.views.generic.simple.redirect_to', {'url': 'show/Start'}),
                                              )
urlpatterns += patterns('sphene.sphwiki.views',
                        (r'^show/(?P<snipName>[\w/]+)/$', 'showSnip'),
                        (r'^edit/(?P<snipName>[\w/]+)/$', 'editSnip'),
                        (r'^attachments/(?P<snipName>[\w/]+?)/create/$', 'attachmentEdit'),
                        (r'^attachments/(?P<snipName>[\w/]+)/(?P<attachmentId>\d+)/$', 'attachmentEdit'),
                        (r'^attachments/(?P<snipName>[\w/]+)/$', 'attachment'),
                        )

mirror/communitytools/trunk/sphenecoll/sphene/community/models.py
from django.db import models

# Create your models here.

class Group(models.Model):
	name = models.CharField(maxlength = 250)
	longname = models.CharField(maxlength = 250)
	default_theme = models.ForeignKey('Theme', null = True, blank = True)
	parent = models.ForeignKey('Group', null = True, blank = True)
        baseurl = models.CharField(maxlength = 250)

        def get_name(self):
                return self.longname or self.name

        def recursiveName(self):
                recname = ''
                if self.parent:
                        recname = self.parent.recursiveName() + ' / '
                return recname + self.name

	def __str__(self):
		return self.name;

	class Admin:
		pass
	

class Theme(models.Model):
	name = models.CharField(maxlength = 250)
	path = models.CharField(maxlength = 250)

	def __str__(self):
		return self.name;

	class Admin:
		pass

NAVIGATION_URL_TYPES = (
        (0, 'Relative (e.g. /wiki/show/Start)'),
        (1, 'Absolute (e.g. http://sphene.net')
        )

NAVIGATION_TYPES = (
        (0, 'Left Main Navigation'),
        (1, 'Top navigation')
        )

class Navigation(models.Model):
        group = models.ForeignKey(Group)
        label = models.CharField(maxlength = 250)
        href  = models.CharField(maxlength = 250)
        urltype = models.IntegerField( default = 0, choices = NAVIGATION_URL_TYPES )
        sortorder = models.IntegerField( default = 100 )
        navigationType = models.IntegerField( default = 0, choices = NAVIGATION_TYPES )


        def __str__(self):
                return self.label

        class Meta:
                ordering = ['sortorder']

        class Admin:
                list_display = ( 'label', 'group', 'href', 'navigationType' )
                list_filter = ( 'group', 'navigationType' )
                ordering = ['group', 'navigationType', 'sortorder']
        

mirror/communitytools/trunk/sphenecoll/sphene/sphboard/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

from sphene.community.models import Group

from django.utils import html
from text import bbcode
from datetime import datetime

import re

POSTS_ALLOWED_CHOICES = (
    (-1, 'All Users'),
    (0, 'Loggedin Users'),
    (1, 'Members of the Group'),
    (2, 'Administrators'),
    (3, 'Nobody'),
    )

# Create your models here.
class Category(models.Model):
    name = models.CharField(maxlength = 250)
    group = models.ForeignKey(Group, null = True, blank = True)
    parent = models.ForeignKey('self', related_name = '_childs', null = True, blank = True)
    description = models.TextField(blank = True)
    allowthreads = models.IntegerField( default = 0, choices = POSTS_ALLOWED_CHOICES )
    allowreplies = models.IntegerField( default = 0, choices = POSTS_ALLOWED_CHOICES )

    def do_init(self, initializer, session, user):
        self._initializer = initializer
        self._session = session
        self._user = user
        self.touch( session, user )

    def get_childs(self):
        return self._childs.all().add_initializer(getattr(self, '_initializer', None))

    def canContainPosts(self):
        return self.allowthreads != 3

    def thread_list(self):
        return self.posts.filter( thread__isnull = True )

    def threadCount(self):
        return self.posts.filter( thread__isnull = True ).count()

    def postCount(self):
        return self.posts.count()

    def latestPost(self):
        return self.posts.latest( 'postdate' )

    def allowPostThread(self, user):
        return self.testAllowance(user, self.allowthreads)

    def testAllowance(self, user, level):
        if level == -1:
            return True;
        if user == None or not user.is_authenticated():
            return False;
        if level == 0:
            return True;
        return False;

    """
      Touches the category object by updating 'lastVisit'
      Returns the datetime object of when it was last visited.
    """
    def touch(self, session, user):
        # Check if we were already "touched" ;)
        if getattr(self, '_touched', False): return self._lastVisit
        self._touched = True
        self.hasNewPosts = self._hasNewPosts(session, user)
        if not user.is_authenticated(): return None
        try:
            lastVisit = CategoryLastVisit.objects.get( category = self, user = user )
            sKey = self._getSessionKey()
            val = session.get( sKey )
            if not val or not val.has_key( 'originalLastVisit' ):
                val = { 'originalLastVisit': lastVisit.lastvisit,
                        'originalLastVisitSet': datetime.today(), }
                session[sKey] = val
            self._lastVisit = val['originalLastVisit']
        except CategoryLastVisit.DoesNotExist:
            lastVisit = CategoryLastVisit(user = user, category = self)
            self._lastVisit = datetime.today()
        lastVisit.lastvisit = datetime.today()
        lastVisit.save()
        return self._lastVisit

    def _hasNewPosts(self, session, user):
        if not user.is_authenticated(): return False
        try:
            latestPost = Post.objects.filter( category = self ).latest( 'postdate' )
        except Post.DoesNotExist:
            return False
        
        sKey = self._getSessionKey()
        val = session.get( sKey )
        if not val or not val.has_key('originalLastVisit'):
            # if no original lastvisit is stored, load lastvisit from DB.
            try:
                lastVisit = CategoryLastVisit.objects.get( category = self, user = user )
            except CategoryLastVisit.DoesNotExist:
                return False
            return lastVisit.lastvisit < latestPost.postdate

        if val['originalLastVisit'] > latestPost.postdate:
            return False

        if not val.has_key('thread_lasthits'):
            return True

        lasthits = val['thread_lasthits']

        # Check all posts to see if they are new ....
        allNewPosts = Post.objects.filter( category = self,
                                           postdate__gt = val['originalLastVisit'], )

        for post in allNewPosts:
            threadid = post.thread and post.thread.id or post.id
            if not lasthits.has_key( threadid ) or lasthits[threadid] < post.postdate:
                return True

        # All posts are read .. cool.. we can remove 'thread_lasthits' and adept 'originalLastVisit'
        del val['thread_lasthits']
        del val['originalLastVisit']
        session[sKey] = val # Store the value back into the session so it gets stored.
        return False

    def _getSessionKey(self):
        return 'sphene_sphboard_category_%d' % self.id;

    def __str__(self):
        return self.name;
    
    class Admin:
        search_fields = ('name')

class CategoryLastVisit(models.Model):
    user = models.ForeignKey(User)
    lastvisit = models.DateTimeField()
    category = models.ForeignKey(Category)

    class Admin:
        list_display = ('user', 'lastvisit')
        list_filter = ('user',)
        pass

ALLOWED_TAGS = {
    'p': ( 'align' ),
    'em': (),
    'strike': (),
    'strong': (),
    'img': ( 'src', 'width', 'height', 'border', 'alt', 'title' ),
    'u': ( ),
    }

#USED_STYLE = 'html'
USED_STYLE = 'bbcode'

def htmlentities_replace(test):
    print "entity allowed: %s" % test.group(1)
    return test.group()

def htmltag_replace(test):
    if ALLOWED_TAGS.has_key( test.group(2) ):
        print "tag is allowed.... %s - %s" % (test.group(), test.group(3))
        if test.group(3) == None: return test.group()
        attrs = test.group(3).split(' ')
        allowedParams = ALLOWED_TAGS[test.group(2)]
        i = 1
        allowed = True
        for attr in attrs:
            if attr == '': continue
            val = attr.split('=')
            if not val[0] in allowedParams:
                allowed = False
                print "Not allowed: %s" % val[0]
                break
        if allowed: return test.group()
    print "tag is not allowed ? %s" % test.group(2)
    return test.group().replace('<','&lt;').replace('>','&gt;')

def bbcode_replace(test):
    print "bbcode ... %s %s %s" % (test.group(1), test.group(2), test.group(3))
    return test.group()
POST_STATUS_DEFAULT = 0
POST_STATUS_STICKY = 1
POST_STATUS_CLOSED = 2
POST_STATUS_POLL = 4

POST_STATUSES = {
    'default': 0,
    'sticky': 1,
    'closed': 2,

    'poll': 4,
    }


class Post(models.Model):
    status = models.IntegerField(default = 0, editable = False )
    category = models.ForeignKey(Category, related_name = 'posts', editable = False )
    subject = models.CharField(maxlength = 250)
    body = models.TextField()
    thread = models.ForeignKey('self', null = True, editable = False )
    postdate = models.DateTimeField( auto_now_add = True, editable = False )
    author = models.ForeignKey(User, editable = False )

    def do_init(self, initializer, session, user):
        self._initializer = initializer
        self.hasNewPosts = self._hasNewPosts(session, user)

    def is_sticky(self):
        return self.status & POST_STATUS_STICKY
    def is_closed(self):
        return self.status & POST_STATUS_CLOSED
    def is_poll(self):
        return self.status & POST_STATUS_POLL

    def set_sticky(self, sticky):
        if sticky: self.status = self.status | POST_STATUS_STICKY
        else: self.status = self.status ^ POST_STATUS_STICKY

    def set_closed(self, closed):
        if closed: self.status = self.status | POST_STATUS_CLOSED
        else: self.status = self.status ^ POST_STATUS_CLOSED

    def set_poll(self, poll):
        if poll: self.status = self.status | POST_STATUS_POLL
        else: self.status = self.status ^ POST_STATUS_POLL

    def get_thread(self):
        if self.thread == None: return self;
        return self.thread;

    def latestPost(self):
        return self.allPosts().latest( 'postdate' )

    def allPosts(self):
        return Post.objects.filter( Q( pk = self.id ) | Q( thread = self ) )

    def postCount(self):
        return self.allPosts().count()

    def allowPosting(self, user):
        return self.category.testAllowance( user, self.category.allowreplies )


    def body_escaped(self):
        body = self.body
        if USED_STYLE == 'html':
            regex = re.compile("&(?!nbsp;)");
            body = regex.sub( "&amp;", body )
            regex = re.compile("<(/?)([a-zA-Z]+?)( .*?)?/?>")
            return regex.sub( htmltag_replace, body )
        else:
            """
            body = html.escape( body )
            body = html.linebreaks( body )
            regex = re.compile("\[(.*?)\](?:([^\[]+)\[/(.*?)\])?")
            bbcode = regex.sub( bbcode_replace, body )
            """
            return bbcode.bb2xhtml(body)

    def touch(self, session, user):
        return self._touch( session, user )

    def _touch(self, session, user):
        if not user.is_authenticated(): return None
        if not self._hasNewPosts(session, user): return
        sKey = self.category._getSessionKey()
        val = session.get( sKey )
        if not val: val = { }
        if not val.has_key( 'thread_lasthits' ): val['thread_lasthits'] = { }
        val['thread_lasthits'][self.id] = datetime.today()
        session[sKey] = val

    def _hasNewPosts(self, session, user):
        if not user.is_authenticated(): return False
        try:
            latestPost = Post.objects.filter( thread = self.id ).latest( 'postdate' )
        except Post.DoesNotExist:
            # if no post was found, the thread is the latest post ...
            latestPost = self
        categoryLastVisit = self.category.touch(session, user)
        if categoryLastVisit > latestPost.postdate:
            return False
        sKey = self.category._getSessionKey()
        val = session.get( sKey )

mirror/communitytools/trunk/sphenecoll/sphene/community/views.py
# Create your views here.


from django import newforms as forms
from django.conf import settings
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.template import loader, Context
from django.core.mail import send_mail
from django.contrib.auth import authenticate,login

from utils.misc import cryptString, decryptString

class RegisterEmailAddress(forms.Form):
    email_address = forms.EmailField()


def register(request, group = None):

    if request.method == 'POST':
        form = RegisterEmailAddress(request.POST)
        if form.is_valid():
            regdata = form.clean_data
            email_address = regdata['email_address']
            if group:
                subject = 'Email verification required'
            else:
                subject = 'Email verification required for site %s' % group.get_name()
            validationcode = cryptString( settings.SECRET_KEY, email_address )
            t = loader.get_template('sphene/community/accounts/account_verification_email.txt')
            c = {
                'email': email_address,
                'baseurl': group.baseurl,
                'validationcode': validationcode,
                'group': group,
                }
            send_mail( subject, t.render(RequestContext(request, c)), None, [email_address] )
            return render_to_response( 'sphene/community/register_emailsent.html',
                                       { 'email': email_address,
                                         },
                                       context_instance = RequestContext(request) )
        pass
    else:
        form = RegisterEmailAddress()

    return render_to_response( 'sphene/community/register.html',
                               { 'form': form },
                               context_instance = RequestContext(request) )

username_re = r'^\w+$'

class RegisterForm(forms.Form):
    username = forms.RegexField( username_re )
    email_address = forms.CharField( widget = forms.TextInput( attrs = { 'disabled': 'disabled' } ) )
    password = forms.CharField( widget = forms.PasswordInput )
    repassword = forms.CharField( label = 'Verify Password', widget = forms.PasswordInput )

    def clean(self):
        if self.clean_data['password'] != self.clean_data['repassword']:
            raise forms.ValidationError("Passwords do not match.")
        return self.clean_data


def register_hash(request, emailHash, group = None):
    email_address = decryptString( settings.SECRET_KEY, emailHash )
    if request.method == 'POST':
        post = request.POST.copy()
        post.update( { 'email_address': email_address } )
        form = RegisterForm( post )
        if form.is_valid():
            formdata = form.clean_data
            user = User.objects.create_user( formdata['username'],
                                             formdata['email_address'],
                                             formdata['password'], )
            user = authenticate( username = formdata['username'], password = formdata['password'] )
            login(request, user)
            return render_to_response( 'sphene/community/register_hash_success.html',
                                       { },
                                       context_instance = RequestContext(request) )
    else:
        form = RegisterForm( )
        form.fields['email_address'].initial = email_address
    return render_to_response( 'sphene/community/register_hash.html',
                               { 'form': form },
                               context_instance = RequestContext(request) )

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/_displayBreadcrumbs.html
<a href="../../show/0/">Board</a>
{% if categories %}
  {% for category in categories %}
    &gt;&gt; 
    {% ifnotequal category current %}
      <a href="../../show/{{ category.id }}/">{{ category.name }}</a>
    {% else %}
      {{ category.name }}
    {% endifnotequal %}
  {% endfor %}
{% endif %}
{% if thread %}
  &gt;&gt;
  {% if linkall %}
    <a href="../../thread/{{ thread.id }}/">{{ thread.subject }}</a>
  {% else %}
    {{ thread.subject }}
  {% endif %}
{% endif %}

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/_displayCategories.html
{% load sphboard_extras %}

{% for category in categories %}
  <tr>
    {% for test in level|sphrange %}
      <td width='5px'>&nbsp;</td>
    {% endfor %}
    <td width="20px"><img src="/static/sphene/sphboard/icons/{% if category.hasNewPosts %}new{% endif %}folder.gif" width='16px' height='16px' /></td>
    <td class="sphboard_categoryname" colspan='{{ maxDepth|sphminus:level }}'><a href="../{{ category.id }}/">{{ category.name }}</a><br/><small>{{ category.description }}</small></td>
    <td class="sphboard_threadcount">{{ category.threadCount }}</td>
    <td class="sphboard_postcount">{{ category.postCount }}</td>
    <td class="sphboard_latestpost">{% sphboard_latestPost category.latestPost %}</td>
  </tr>
  {% sphboard_displayCategories category.get_childs maxDepth level %}
{% endfor %}

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/_displayLatestPost.html
{% load sphboard_extras %}
{% if latestPost %}
  {% ifequal showSubject 1 %}
    <a href="../../thread/{{ latestPost.get_thread.id }}/">{{ latestPost.subject }}</a>
    at {{ latestPost.postdate|date:"Y-m-d H:i:s" }}<br/>
  {% else %}
    At <a href="../../thread/{{ latestPost.get_thread.id }}/">{{ latestPost.postdate|date:"Y-m-d H:i:s" }}</a><br/>
  {% endifequal %}
  By {% sphboard_displayUserName latestPost.author %}
{% else %}
  No Posts Yet.
{% endif %}

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/_displayPostForm.html
<style>
  .sphboard { width: 100%; }
  textarea { width: 100%; }
  .sphboard input { width: 100%; }
</style>

<form method="POST" action="." name="postform">
  <input type="hidden" name="category" value="{{ category.id }}" />
  {% if thread %}
    <input type="hidden" name="thread" value="{{ thread.id }}" />
  {% endif %}
  <table class="sphboard form">
    {{ form }}
  </table>

  {% if not thread %}
  <input type="checkbox" name="createpoll" value="1" onchange="javascript:document.getElementById( 'poll' ).style.display = (this.checked ? 'block' : 'none' )" id="createpoll_id"{% if createpoll %} checked="checked"{% endif %} /> <label for="createpoll_id">Add a poll to this thread</label><br/><br/>

  <div id="poll" style="display: none">
    <table class="sphboard form">
      <tr>
        <th colspan="2">Poll</th>
      </tr>
      {{ pollform }}
    </table>
  </div>
  <script language="JavaScript">
  <!--
    document.getElementById( 'poll' ).style.display = (document.postform.createpoll.checked ? 'block' : 'none');
  //-->
  </script>
  {% endif %}

  <input type="submit" value="Post" />

</form>

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/_displayUserName.html
{% if user.first_name or user.last_name %}
  {{ user.first_name }} {{ user.last_name }} ({{ user.username }})
{% else %}
  {{ user.username }}
{% endif %}

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/_pagination.html
Page:
{% if has_prev %}
  <a href="?page={{ prev }}">Previous</a>
{% endif %}
{% for p in page_range %}
  {% ifequal p page %}
    {{ p }}
  {% else %}
    <a href="?page={{ p }}">{{ p }}</a>
  {% endifequal %}
{% endfor %}
{% if has_next %}
  <a href="?page={{ next }}">Next</a>
{% endif %}

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/base.html
{% extends "sphene/base.html" %}

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/listCategories.html
{% extends "sphene/sphboard/base.html" %}

{% load sphboard_extras %}
{% load humanize %}

{% block content %}

  <a href="../../latest/{{ category_id }}/">Latest</a> | {% sphboard_displayBreadcrumbsForCategory category %}<br/><br/>

  {% if rootCategories %}
  <table class="sphboard_categories">
    <tr>
      <th colspan='6'>Title</th>
      <th>Threads</th>
      <th>Posts</th>
      <th>Last Post</th>
    </tr>
    {% sphboard_displayCategories rootCategories 5 %}
  </table>
  <br/><br/>
  {% endif %}

  {% if isShowLatest or category.canContainPosts %}
    <table class="sphboard_thread_list">
      <tr>
        <th class="sphboard_mainhead" colspan="4">Threads</th>
      </tr>
      <tr>
        <th colspan="2">Subject / Author</th>
        <th>Posts</th>
        <th>Last Post</th>
      </tr>
      {% for thread in thread_list %}
        <tr>
          <td width="20px"><img src="/static/sphene/sphboard/icons/{% if thread.hasNewPosts %}new{% endif %}folder.gif" width='16px' height='16px' /></td>
          <td>{% if thread.is_sticky %}<b>Sticky:</b> {% endif %}{% if thread.is_poll %}Poll: {% endif %}<a href="../../thread/{{ thread.id }}/">{{ thread.subject }}</a><br/><small>{% if isShowLatest %}{% sphboard_displayBreadcrumbsForCategory thread.category 1 %} - {% endif %}by {% sphboard_displayUserName thread.author %}</small></td>
          <td class="sphboard_postcount">{{ thread.postCount }}</td>
          <td class="sphboard_latestpost">{% sphboard_latestPost thread.latestPost 0 %}
        </tr>
      {% endfor %}
      <tr>
        <td colspan="4"><span style="float:left;">{{ hits }} Threads in this category yet.</span><span style="display:block;float:right;">{% sphboard_pagination pages page %}</span></td>
      </tr>
    </table>
    <br/><br/>
    {% if allowPostThread %}
      <a href="../../post/{{ category.id }}/">Post New Thread</a>
      {# sphboard_displayPostForm #}
    {% else %}
      {% if user.is_authenticated %}
        You have no permission to create a new thread.
      {% else %}
        Please login to create a new thread.
      {% endif %}
    {% endif %}
  {% endif %}

  <br/><br/>

{% endblock %}

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/post.html
{% extends "sphene/sphboard/base.html" %}

{% load sphboard_extras %}

{% block content %}

  {% if thread %}
    {% sphboard_displayBreadcrumbsForThread thread 1 %}
  {% else %}
    {% sphboard_displayBreadcrumbsForCategory category 1 %}
  {% endif %}<br/><br/>

  {% if thread %}
    <b>Posting reply to thread {{ thread.subject }}.</b>
  {% else %}
    <b>Posting new thread.</b>
  {% endif %}<br/><br/>

  {% include "sphene/sphboard/_displayPostForm.html" %}

{% endblock %}

mirror/communitytools/trunk/sphenecoll/templates/sphene/sphboard/showThread.html
{% extends "sphene/sphboard/base.html" %}

{% load sphboard_extras %}

{% block content %}
  {% sphboard_displayBreadcrumbsForThread thread %}
  <br/>
  {% if perms.post.change_post %}
    Thread Options: 
      {% if thread.is_sticky %}
        <a href="../../options/{{ thread.id }}/?cmd=removeSticky">Remove Sticky</a>
      {% else %}
        <a href="../../options/{{ thread.id }}/?cmd=makeSticky">Make Sticky</a>
      {% endif %}
      <br/>
  {% endif %}
  <br/>
  <table class="sphboard_post_list">
    {% for post in post_list %}
      <tr>
        <td rowspan="2" class="sphboard_post_authorinfo">
          Posted by<br/>
          {% sphboard_displayUserName post.author %}<br/>
        </td>
        <td>{{ post.postdate|date:"Y-m-d H:i:s" }} - <strong>{{ post.subject|escape }}</strong></td>
      </tr>
      <tr>
        <td class="sphboard_post_body">{{ post.body_escaped }}</td>
      </tr>
      {% ifequal post thread %}
        {% if post.poll %}
          <tr>
            <td colspan='2'>
              <b>Poll: {{ post.poll.question }}</b><br/><br/>
              {% if post.poll.has_voted %}
                You already voted. Here are the results ({{ post.poll.total_voters }} votes total - {% widthratio post.poll.null_votes post.poll.total_votes 100 %}% did not answer):
                <table class="sphboard polls_results">
                  {% for choice in post.poll.choices %}
                    <tr>
                      <td align="right" style="white-space:nowrap;">{% widthratio choice.count post.poll.total_votes 100 %}%</td>
                      <td width="100%"><span style="background-color:#cccccc;font-size:5px;height:10px;padding-right:{% widthratio choice.count post.poll.total_votes 500 %}px;">&nbsp;</span><br/>{{ choice.choice }}</td>
                    </tr>
                  {% endfor %}
                </table>
              {% else %}
                <form method="POST" action="../../vote/{{ thread.id }}/">
                {% if request.attributes.voteerror %}
                  <strong class="sphboard error">Error: {{ request.attributes.voteerror }}</strong><br/>
                {% endif %}
                {% if post.poll.multiplechoice %}
                  You may select up to {{ post.poll.choices_per_user }} answers:
                  <ul style="list-style: none">
                    {% for choice in post.poll.choices %}
                      <li><input type="checkbox" name="pollchoice" value="{{ choice.id }}" id="pollchoice_{{ choice.id }}" /> <label for="pollchoice_{{ choice.id }}">{{ choice.choice }}</label></li>
                    {% endfor %}
                    <li><input type="checkbox" name="pollchoice" value="0" id="pollchoice_0" /> <label for="pollchoice_0">Show Results (You won't be able to vote.)</label></li>
                  </ul>
                {% else %}
                  <ul style="list-style: none">
                    {% for choice in post.poll.choices %}
                      <li><input type="radio" name="pollchoice" value="{{ choice.id }}" id="pollchoice_{{ choice.id }}" /> <label for="pollchoice_{{ choice.id }}">{{ choice.choice }}</label></li>
                    {% endfor %}
                    <li><input type="radio" name="pollchoice" value="0" id="pollchoice_0" /> <label for="pollchoice_0">Show Results (You won't be able to vote.)</label></li>
                  </ul>
                {% endif %}
                {% if user.is_authenticated %}
                  <input type="submit" value="Vote" />
                {% else %}
                  You need to be logged in to vote.
                {% endif %}
                </form>
              {% endif %}
            </td>
          </tr>
        {% endif %}
      {% endifequal %}
    {% endfor %}
  </table>
  <br/><br/>
  
  {% if allowPosting %}
    <a href="../../post/{{ thread.category.id }}/?thread={{ thread.id }}">Post Reply</a>
    {# sphboard_displayPostForm thread #}
  {% else %}
    {% if user.is_authenticated %}
      You have no permission to post a reply.
    {% else %}
      Please login to post a reply.
    {% endif %}
  {% endif %}
  <br/><br/>
{% endblock %}